# Alpine Linux miniconda with Jupyter r
# youske/alpine-jupyter based

FROM youske/alpine-jupyter:latest
MAINTAINER youske miyakoshi <youske@gmail.com>

LABEL com.geeplus.description="alpine jupyter r image" \
      com.geeplus.role="jupyter r image"

# r package
RUN conda install -c r r-essentials 
